import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Particles from "@/components/Particles";
import CustomCursor from "@/components/CustomCursor";
import { Footer } from "@/components/footer"; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Dharun Nagavel - Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) 
{
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="custom-cursor" id='cur'>
          <CustomCursor />
        </div>
        <div className="fixed inset-0 -z-10">
          <Particles
            particleColors={['#fde047']}
            particleCount={500}
            particleSpread={20}
            speed={0.1}
            particleBaseSize={100}
            moveParticlesOnHover={true}
            alphaParticles={false}
            particleHoverFactor={2} 
            disableRotation={false}
          />
        </div>
        <main className="relative z-10 min-h-screen">
          <Navbar/>
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}